// <auto-generated />
namespace Sistema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class P1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(P1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010231932502_P1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
